type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "This will be having all the transformation jobs for DDL"
  components:
    BANK TXNS INPUT TABLE:
      type: "table-input"
      parameters:
        componentName: "BANK TXNS INPUT TABLE"
        database: "BANKING"
        schema: "BANKING_SCHEMA"
        targetTable: "TXNS"
        columnNames:
        - "TRANS_ID"
        - "ACCOUNT_ID"
        - "DATE"
        - "TYPE"
        - "OPERATION"
        - "AMOUNT"
        - "BALANCE"
        - "PURPOSE"
        - "BANK"
        - "ACCOUNT_PARTNER_ID"
        timeOffset: ""
    Aggregate ACCOUNT_ID:
      type: "aggregate"
      sources:
      - "BANK TXNS INPUT TABLE"
      parameters:
        componentName: "Aggregate ACCOUNT_ID"
        groupings:
        - "ACCOUNT_ID"
        aggregations:
        - - "TRANS_ID"
          - "Count Distinct"
        - - "BALANCE"
          - "Sum"
        groupingType: "Group By"
    Aggregate TXN_YR:
      type: "aggregate"
      sources:
      - "Calculate TXN_YEAR"
      parameters:
        componentName: "Aggregate TXN_YR"
        groupings:
        - "TXN_YEAR"
        aggregations:
        - - "TRANS_ID"
          - "Count Distinct"
        - - "BALANCE"
          - "Sum"
        groupingType: "Group By"
    Calculate TXN_YEAR:
      type: "calculator"
      sources:
      - "BANK TXNS INPUT TABLE"
      parameters:
        componentName: "Calculate TXN_YEAR"
        includeInputColumns: "Yes"
        calculations:
        - - "YEAR(\"DATE\")"
          - "TXN_YEAR"
    Convert Type Date To TimeStamp:
      type: "convert-type"
      sources:
      - "BANK TXNS INPUT TABLE"
      parameters:
        componentName: "Convert Type Date To TimeStamp"
        conversions:
        - - "DATE"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
        - - "BALANCE"
          - "FLOAT"
          - "10"
          - "2"
    Aggregate  BANK:
      type: "aggregate"
      sources:
      - "Calculate TXN_YEAR_BANK"
      parameters:
        componentName: "Aggregate  BANK"
        groupings:
        - "BANK"
        - "TXN_YEAR"
        - "TXN_QTR"
        - "TXN_MNTH"
        aggregations:
        - - "TRANS_ID"
          - "Count Distinct"
        - - "BALANCE"
          - "Min"
        - - "BALANCE"
          - "Max"
        - - "BALANCE"
          - "Average"
        - - "BALANCE"
          - "Sum"
        groupingType: "Group By"
    Calculate TXN_YEAR_BANK:
      type: "calculator"
      sources:
      - "BANK TXNS INPUT TABLE"
      parameters:
        componentName: "Calculate TXN_YEAR_BANK"
        includeInputColumns: "Yes"
        calculations:
        - - "YEAR(\"DATE\")"
          - "TXN_YEAR"
        - - "QUARTER(\"DATE\")"
          - "TXN_QTR"
        - - "MONTH(\"DATE\")"
          - "TXN_MNTH"
    Rename Components:
      type: "rename"
      sources:
      - "Calculate Balance"
      parameters:
        componentName: "Rename Components"
        columnMapping:
        - - "BANK"
          - "BANK"
        - - "TXN_YEAR"
          - "YEAR"
        - - "TXN_QTR"
          - "QTR"
        - - "TXN_MNTH"
          - "MNTH"
        - - "count_distinct_TRANS_ID"
          - "Total Txns"
        - - "ROUND_TOT_BALANCE"
          - "Total Balance"
        - - "min_BALANCE"
          - "Minm Balance"
        - - "max_BALANCE"
          - "Maxm Balance"
        - - "avg_BALANCE"
          - "Avg Balance"
        includeInputColumns: "No"
    Calculate Balance:
      type: "calculator"
      sources:
      - "Aggregate  BANK"
      parameters:
        componentName: "Calculate Balance"
        includeInputColumns: "Yes"
        calculations:
        - - "CAST(CAST(\"sum_BALANCE\"  AS NUMERIC(16,0)) AS bigint)"
          - "ROUND_TOT_BALANCE"
    Next Day Balance:
      type: "lead-lag"
      sources:
      - "BANK TXNS INPUT TABLE"
      parameters:
        componentName: "Next Day Balance"
        includeInputColumns: "Yes"
        partitionData:
        - "ACCOUNT_ID"
        orderingsWithinPartitions:
        - - "DATE"
          - "Asc"
        functions:
        - - "Lead"
          - "BALANCE"
          - "1"
          - "NEXT_DAY_BALANCE"
        ignoreNulls: "Yes"
    Previous Day Balance:
      type: "lead-lag"
      sources:
      - "BANK TXNS INPUT TABLE"
      parameters:
        componentName: "Previous Day Balance"
        includeInputColumns: "Yes"
        partitionData:
        - "ACCOUNT_ID"
        orderingsWithinPartitions:
        - - "DATE"
          - "Desc"
        functions:
        - - "Lag"
          - "BALANCE"
          - "1"
          - "PREV_DAY_BALANCE"
        ignoreNulls: "Yes"
    Rounding Off Balance:
      type: "calculator"
      sources:
      - "Rename Components"
      parameters:
        componentName: "Rounding Off Balance"
        includeInputColumns: "No"
        calculations:
        - - "\"BANK\""
          - "BANK_NAME"
        - - "\"YEAR\""
          - "YEAR"
        - - "\"QTR\""
          - "QTR"
        - - "\"MNTH\""
          - "MNTH"
        - - "ROUND(\"Minm Balance\",0)"
          - "MINM_BALANCE"
        - - "ROUND(\"Maxm Balance\",0)"
          - "MAXM_BALANCE"
        - - "ROUND(\"Avg Balance\",0)"
          - "AVG_BALANCE"
        - - "ROUND(\"Total Balance\",0)"
          - "TOT_BALANCE"
    Create View BANK_TXN_KPI:
      type: "create-view"
      sources:
      - "Rounding Off Balance"
      parameters:
        componentName: "Create View BANK_TXN_KPI"
        database: "BANKING"
        schema: "BANKING_SCHEMA"
        viewName: "BANK_TXN_KPI"
        secureView: "No"
        viewType: "Standard"
design:
  components:
    BANK TXNS INPUT TABLE:
      position:
        x: -1344
        "y": -272
      tempMetlId: 5754
    Aggregate ACCOUNT_ID:
      position:
        x: -1120
        "y": -480
      tempMetlId: 8142
    Aggregate TXN_YR:
      position:
        x: -832
        "y": -384
      tempMetlId: 8253
    Calculate TXN_YEAR:
      position:
        x: -1040
        "y": -384
      tempMetlId: 8323
    Convert Type Date To TimeStamp:
      position:
        x: -912
        "y": -272
      tempMetlId: 8409
    Aggregate  BANK:
      position:
        x: -864
        "y": -160
      tempMetlId: 8501
    Calculate TXN_YEAR_BANK:
      position:
        x: -1152
        "y": -160
      tempMetlId: 8586
    Rename Components:
      position:
        x: -496
        "y": -160
      tempMetlId: 8666
    Calculate Balance:
      position:
        x: -672
        "y": -160
      tempMetlId: 8764
    Next Day Balance:
      position:
        x: -1536
        "y": 0
      tempMetlId: 9072
    Previous Day Balance:
      position:
        x: -1152
        "y": 16
      tempMetlId: 9204
    Rounding Off Balance:
      position:
        x: -352
        "y": -160
      tempMetlId: 9832
    Create View BANK_TXN_KPI:
      position:
        x: -192
        "y": -160
      tempMetlId: 9969
